apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-debugger-sa
  namespace: monitoring  # Recommended to use a dedicated namespace
---
apiVersion: v1
kind: Secret
metadata:
  namespace: monitoring
  name: pod-debugger-sa-secret
  annotations:
    kubernetes.io/service-account.name: pod-debugger-sa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-debugger-role
rules:
- apiGroups: [""]
  resources: ["pods", "events", "namespaces", "nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-debugger-rolebinding
subjects:
- kind: ServiceAccount
  name: pod-debugger-sa
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: pod-debugger-role
  apiGroup: rbac.authorization.k8s.io